### ISSUE TITLE
SMP - nombre maximum des  cœurs de processeurs 

### ISSUE THREAD

**Issue by yellow-panther** [tryingsomestuff/Minic#1]
Combien des UCTs supporte ton programme des échecs Minic? Cette information serait importatante pour une actualisation de CCWiki Chess Engine List http://computer-chess.org/doku.php?id=computer_chess:wiki:lists:chess_engine_list

**Comment by tryingsomestuff** [comment]
Il n'y a a priori pas de limite au nombre de thread mais je suppose qu'au delà de 20 les performances ne seraient pas au rendez-vous !
