### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by AlexB123** [tryingsomestuff/Minic#10]
Hello! Release 2.15 Windows and android version not working, engine crashes instantly.

**Comment by tryingsomestuff** [comment]
Thanks for reporting. This is tollaly right. In fact UCI is not working. I'll patch today.
You an still play in xboard mode using the -xboard command line argument.

**Comment by tryingsomestuff** [comment]
ok this is fixed. Thanks again. Release 2.16 will do the job.
