### ISSUE TITLE
how to use genfen ?

### ISSUE THREAD

**Issue by deedstacktyk** [tryingsomestuff/Minic#12]
Hi Viven, i wanted to try your genfen command but i had failed :

minic_2.52_mingw_x64_skylake.exe (<= i'm on a E5-1650v4 rig)
info string This is Minic version 2.52 (NNUE available)
info string Info  2020-10-16 11:16:01-597: No NNUE net given
info string Info  2020-10-16 11:16:01-598: Classical evaluation enabled.
uci
id name Minic 2.52
id author Vivien Clauzon
option name Level type spin default 100 min 0 max 100
option name UCI_LimitStrength type check default false
option name UCI_Elo type spin default 1500 min 500 max 2800
option name Hash type spin default 128 min 1 max 256000
option name Threads type spin default 1 min 1 max 255
option name UCI_Chess960 type check default false
option name Ponder type check default false
option name MateFinder type check default false
option name MultiPV type spin default 1 min 1 max 4
option name Contempt type spin default 12 min -50 max 50
option name ContemptMG type spin default 12 min -50 max 50
option name SyzygyPath type string default
option name NNUEFile type string default
option name forceNNUE type check default false
option name GenFen type check default false
option name GenFenDepth type spin default 8 min 2 max 20
option name GenFenSkip type spin default 1 min 0 max 10000000
option name StyleAttack type spin default 50 min 0 max 100
option name StyleComplexity type spin default 50 min 0 max 100
option name StyleDevelopment type spin default 50 min 0 max 100
option name StyleMaterial type spin default 50 min 0 max 100
option name StyleMobility type spin default 50 min 0 max 100
option name StylePositional type spin default 50 min 0 max 100
option name StyleForwardness type spin default 50 min 0 max 100
uciok
setoption name GenFenDepth value 2
setoption name GenFenSkip value 100
setoption name GenFen value true
go
info string Fatal 2020-10-16 11:16:24-043: bad timing configuration ... (missing dynamic time info for sudden death style TC)

**Comment by tryingsomestuff** [comment]
Hi you did well ! 
But my genfen feature is not working as SF one. It will work "during" a real game.
You can use 3 modes for generating fen inside Minic.
1°) just run many game at fixed depth in cutechess or you favorite gui and save to pgn.
Then use something like pgn-extract --fencomments -Wlalg --nochecks --nomovenumbers --noresults -w500000 -N -V -o data.plain games.pgn
And then use Minic -png2bin command
2°) set up Minic with genfen option (as you did !) in your GUI and then run Minic in random mode versus itself in random mode (level=0). This will generate sfen analyzed at depth "GenFenDepth" from random position
3°) use the "game tree" gen fen thing. So indeed set GenFen options with GenFenSkip to some quite big number like 100 or even 1000. And in your GUI run many games Minic versus Minic a very small TC or small fixed depth.

Let me know if you're in success. Those features are quite obscur for know, I wasn't expecting somebody to gives interest to that. So thanks a lot for you interest !!

**Comment by tryingsomestuff** [comment]
I added some doc in the README.md
