### ISSUE TITLE
how to train a net with minic ?

### ISSUE THREAD

**Issue by deedstacktyk** [tryingsomestuff/Minic#13]
Hi Viven, after generating data in PLAIN TEXT format (sfens compatible), Minic -plain2bin is used to convert this data to NNUE BIN format. But how do you train a net with Minic ?

**Comment by tryingsomestuff** [comment]
Here it is (from Seer repo)

https://github.com/tryingsomestuff/Minic/tree/master/train

**Comment by deedstacktyk** [comment]
Even with device: 'cpu' into config.yaml, i got a "nvidia gpu cuda drivers" error, it's weird :

C:\Downloads\train>py train.py
C:\python\lib\site-packages\torch\cuda\__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your
system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (
Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "train.py", line 96, in <module>
    main()
  File "train.py", line 60, in main
    writer.add_graph(M, sample_to_device(next(iter(train_data_loader)))[:3])
  File "C:\python\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "C:\python\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\python\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
    w.start()
  File "C:\python\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\python\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\python\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\python\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\python\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: 'NoneType' object is not callable

C:\Downloads\train>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\python\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\python\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by tryingsomestuff** [comment]
No this is classic stuff unfortunatly.

conda uninstall pytorch
conda install -c peterjc123 pytorch-cpu

**Comment by deedstacktyk** [comment]
again an error :
conda install -c peterjc123 pytorch-cpu

(base) C:\Users\nom>conda install -c peterjc123 pytorch-cpu
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible so
lve.
Solving environment: failed with repodata from current_repodata.json, will retry
 with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible so
lve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pytorch-cpu -> python[version='>=3.5,<3.6.0a0|>=3.6,<3.7.0a0']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked
 for.
When python appears to the right, that indicates that the thing on the left is s
omehow
not available for the python version you are constrained to. Note that conda wil
l not
change your python version to a different minor version unless you explicitly sp
ecify
that.

So if Minic/seer are as so buggued as nodchip, it's enough for me, best luck dudes
