### ISSUE TITLE
Bad display in Multi-PV mode

### ISSUE THREAD

**Issue by BrennusJ** [tryingsomestuff/Minic#15]
Is seems in multi-PV mode that different line get the same first ply, look 1. Fb5 and 3. Fb5 , to be displayed as different line the first ply should be different
(in French : Il me semble que pour être afficher comme une ligne distincte, le 1er coup doit être different)
![Capture d’écran_2020-11-21_20-27-56](https://user-images.githubusercontent.com/3634605/99886092-0c3d4780-2c3a-11eb-978d-8cf4ceb0bd3f.png)

**Comment by tryingsomestuff** [comment]
Thanks for reporting. This is a display issue, because PV is restored from hash table. I'll fix that soon.
Thanks for using Minic.

**Comment by tryingsomestuff** [comment]
fixed in a9d4a89f6c2952f2c60de618eb52c1e3b101eaf3
