### ISSUE TITLE
RPi4 binary works!

### ISSUE THREAD

**Issue by kenpchess** [tryingsomestuff/Minic#16]
Hello, Vivien! Sorry, I do not have a talkchess account.

Yes indeed, your binary for the RPi4 works! Thank you. FYI, I am running the standard Raspbian on a Pi4 (I believe Raspbian on Pi4 is essentially 32-bit with popcnt instructions? The Pi4 with Raspbian is called an armv7-neon build.).

I had been trying to compile Minic on the raspberry pi4 without success! So thanks very much! Can you possibly share your compile commands, etc.? (Even though you apparently cross-compiled it, the compile commands info would be useful to me.).

At any rate, thanks again! I like Minic very much!

- Ken

**Comment by tryingsomestuff** [comment]
Good to know !
Here is the build script
https://github.com/tryingsomestuff/Minic/blob/master/Tools/buildRPi4.sh
with two major incredient : 
- -DWITHOUT_FILESYSTEM (because of g++<9 in the RPi4 toolkit, no proper std::filesystem)
- -static-libgcc -static-libstdc++

Regards
