### ISSUE TITLE
command line parameters

### ISSUE THREAD

**Issue by BrennusJ** [tryingsomestuff/Minic#19]
Bonjour,

line commande interface

i want to set it less verbose ton minmise output : it quiclky overflow the Scid-vs-PC standard limit of 5000 lines and then for strange reason scid-vs-PC stop to use it (unstead of rotate logs)
I don't understand clearly how to make it less verbose and i try this : 

$ ./minic_3.03_linux_x64_skylake -quiet 1
info string This is Minic version 3.03 (NNUE available)
info string Info  2021-02-14 08:57:20-756: No NNUE net loaded, using standard evaluation
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::at: __n (which is 1) >= this->size() (which is 1)
Abandon (core dumped)
$

i don't understand why the executable seems to crash for a bad or mistake entry, in case of unrecognise command it could be send back to console a generic error message or keep silence (like other engine)
"quiet" is not available in uci option

may be something i don't understand in link with double protocol handled (UCI + xboard)

Merci

Jérôme

**Comment by tryingsomestuff** [comment]
Hi,
default verbosity is low. This means just running ./minic will result in (most) only GUI ouput
```
info string This is Minic version 3.04 (NNUE available)
info string Info  2021-02-14 09:28:14-915: No NNUE net loaded, using standard evaluation
go depth 6
info depth 1 score cp 102 time 1 nodes 21 nps 20999 seldepth 1 tbhits 0 pv b1c3 
info depth 2 score cp 45 time 1 nodes 62 nps 61999 seldepth 2 tbhits 0 pv b1c3 b8c6 
info depth 3 score cp 91 time 1 nodes 90 nps 89999 seldepth 3 tbhits 0 pv b1c3 b8c6 g1f3 
info depth 4 score cp 58 time 1 nodes 171 nps 170999 seldepth 4 tbhits 0 pv e2e3 b8c6 b1c3 g8f6 
info depth 5 score cp 53 time 1 nodes 475 nps 474999 seldepth 6 tbhits 0 pv c2c4 b8c6 b1c3 g8f6 g1f3 
info depth 6 score cp 72 time 1 nodes 806 nps 805999 seldepth 6 tbhits 0 pv b1c3 b8c6 h2h3 g8f6 g1f3 e7e6 
bestmove b1c3 ponder b8c6
```

When you ask -quiet 1 from the command line, you need to specify a protocol first (this is indeed not enough intuitive)
```
./minic -uci -quiet 1
./minic -xboard -quiet 1
```

I'll make that simpler soon.
Thanks

**Comment by tryingsomestuff** [comment]
In fact this shall be covered by "illegal" fen input BUT I just saw this horrible mistake inside fen parsing

```
while ((j <= NbSquare) && (i <= (char)strList[0].length())){
```

should be 

```
while ((j <= NbSquare) && (i < (char)strList[0].length())){
```

Thanks ;)

**Comment by tryingsomestuff** [comment]
fixed in master : https://github.com/tryingsomestuff/Minic/commit/41afc37da6afb0f26fe734a92ce113398f95fd49
