### ISSUE TITLE
Mac OS compilé bmi.2 et x64 - Jase de Lace ("Spill The Tea")

### ISSUE THREAD

**Issue by yellow-panther** [tryingsomestuff/Minic#2]
Salut Vivien,

cf. un lien de téléchargement ici: https://drive.google.com/file/d/1yJ73deW13uTXqIsO8rnRwkUtXVXF0Sug/view 

Pourrais-tu créér un fichier binaire avec Windows 32-bit (pour les futures versions) ,  s'il te plaît?

Meilleures salutations,

**Comment by tryingsomestuff** [comment]
I ll try
