### ISSUE TITLE
3-fold misevaluation

### ISSUE THREAD

**Issue by dav1312** [tryingsomestuff/Minic#26]
https://www.chess.com/computer-chess-championship#event=ccc-19-blitz-qualifier-2&game=143

**Comment by tryingsomestuff** [comment]
Very interesting one. Thanks for reporting.

**Comment by tryingsomestuff** [comment]
some test has been done.
Not using 3rep in Minic is loosing around 45Elo.
When I try to fix this lose 3Elo.

What is striking is that Minic immediatly go for the draw line after g5
```
info depth 26 score cp 190 time 9183 nodes 1319805879 nps 143722741 seldepth 36 tbhits 0 pv c2c1 c5b3 c1c2 b3c5 c2d2 c5b3 d2c2 b3c5 e2d1 d8e7 g1f1 f7f6 c3e2 c8d7 e2g3 g8h8 f1g1 a5a4 g3f5 d7f5 g4f5 f8f7 e3f2 e7d7 f2h4 g5h4 
243278 
bestmove c2c1 ponder c5b3
```
but with +1.9 score

I'll patch soon anyway. Thanks again.

**Comment by tryingsomestuff** [comment]
I finally understood what was the issue here !
The first time the repeated position appeared was after a double pawn push. In Minic this lead to a different hash than the same position without the en-passant posibility.

**Comment by tryingsomestuff** [comment]
but i also find this : "Two positions are by definition "the same" if the same types of pieces occupy the same squares, the same player has the move, the remaining castling rights are the same and **the possibility to capture en passant is the same**."

**Comment by tryingsomestuff** [comment]
I think the bug is that I set ep square event if it cannot be usefull

**Comment by dav1312** [comment]
> "Two positions are by definition "the same" if the same types of pieces occupy the same squares, the same player has the move, the remaining castling rights are the same and **the possibility to capture en passant is the same**."

Yeah I think the last part is a little bit confusing. It was a double push pawn which enables the possibility of en passant but because there is no pawn that can do en passant that possibility doesn't really exist 🤔

For example, Wikipedia says that after `1. e4` the FEN should be `rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1` even tho it's impossible for the pawn to be captured.
Some GUIs like chess.com or Arena use that FEN but other ones like Lichess or Nibbler don't display the en passant square in the FEN.

**Comment by tryingsomestuff** [comment]
indeed. Now using
```
if (pawnMove && abs(moveInfo.to - moveInfo.from) == 16 && (BBTools::adjacent(SquareToBitboard(moveInfo.to)) & p.pieces_const(~p.c,P_wp)) != emptyBitBoard) {
```
to set EP square. This is fixing this specific issue at least ;)

**Comment by tryingsomestuff** [comment]
Thanks again for reporting, i'll commit soon and close the issue now.
