### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by SzotsGabor** [tryingsomestuff/Minic#29]
Usingthe makefile, I have this message after the net has been downloaded:

Cloning into 'Fathom'...
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -ldl: No such file or directory
collect2.exe: error: ld returned 1 exit status

What does it mean?

**Comment by tryingsomestuff** [comment]
it seems you are try a Windows build under mingw32. This is not supported with the current makefile or build process.

You can use a provided cross-compiled Windows binary directly for now.

I'll try to see later if I can do a something for this kind of plateform.

**Comment by SzotsGabor** [comment]
> You can use a provided cross-compiled Windows binary directly for now.

Thanks, I'll do that.

**Comment by tryingsomestuff** [comment]
By the way, I check if native windows MSVC built are faster or not than the cross-compiled ones I release. And it seems **not**. I'm a bit surprised by that. Of course I did not try some kind of PGO under Windows, which may lead to better perf, but at least those cross-compiled binaries are not too bad. I'll thus close this as "won't fix".
