### ISSUE TITLE
Minic 1.19 avec ChessGUI 0.245m

### ISSUE THREAD

**Issue by yellow-panther** [tryingsomestuff/Minic#6]
Salut Vivien,
cf. ajouté - fichiers de débogage pour cette interface http://www.chess.hylogic.de/ 
Matthias est aussi un membre du forum https://lefouduroi.pagesperso-orange.fr/tournois/uci/uel.htm
[DEBUG.zip](https://github.com/tryingsomestuff/Minic/files/4005256/DEBUG.zip)

Meilleurs salutations,
Norbert

**Comment by tryingsomestuff** [comment]
Thanks for the report. 
Having a look at the debug file given, I wonder if your are not trying to use xboard protocol with Minic in UCI mode. Are you using -uci or -xboard for your minic executable ?

**Comment by yellow-panther** [comment]
Rybka 2.3.2a > UCI2, Minic 1.19 > WB2 (paramètres de ligne de commande -xboard)
Est-ce que Minic v1.00 la première édition avec le protocole UCI http://download.shredderchess.com/div/uci.zip ?

**Comment by tryingsomestuff** [comment]
Must say UCI didn't work so well in previous versions. 1.15 is probably a safer version.
I have absolutely no issue with winboard (xboard mode) or with cutechess (xboard or uci). I'll try other GUI very soon.

**Comment by yellow-panther** [comment]
cf.
http://computer-chess.org/doku.php?id=computer_chess:wiki:lists:gui_protocol_support_list

Am Fr., 27. Dez. 2019 um 13:40 Uhr schrieb tryingsomestuff <
notifications@github.com>:

**Comment by tryingsomestuff** [comment]
Shall be fixed in 1.21 ;)
