### ISSUE TITLE
Compile errors on a Raspberry Pi 3b+

### ISSUE THREAD

**Issue by ScallyBag** [tryingsomestuff/Minic#7]
Hi,

I’ve been compiling Minic fine lately for Picochess on a Raspberry Pi, however after pulling your latest code it fails:

Building minic_dev
-s -Wall -Wno-char-subscripts -Wno-reorder -DDEBUG_TOOL -DNDEBUG -O3 -flto -march=native --std=c++14
/tmp/ccFQMIs7.ltrans23.ltrans.o: In function `BBTools::initMask()':
<artificial>:(.text+0x47b0): undefined reference to `BBTools::Mask::ranks'
<artificial>:(.text+0x47b8): undefined reference to `BBTools::Mask::ranks'
collect2: error: ld returned 1 exit status
/tmp/ccuv5ihP.ltrans28.ltrans.o: In function `BBTools::initMask()':
<artificial>:(.text+0x3310): undefined reference to `BBTools::Mask::ranks'
<artificial>:(.text+0x3314): undefined reference to `BBTools::Mask::ranks'
collect2: error: ld returned 1 exit status

Thanks,

Alan Cooper

**Comment by tryingsomestuff** [comment]
Indeed, is already fixed at home. Will push soon. Thanks for reporting.
