### ISSUE TITLE
Minic Playing Musketeer Chess Variant

### ISSUE THREAD

**Issue by musketeerchess** [tryingsomestuff/Minic#8]
Hi
There is growing interest in Musketeer Chess Variant. I'mZied, the inventor. I'm a medical doctor working in France. currently i help fight against Covid-19 and help critically ill patients to recover. Not an easy task.

Recently Stockfish joined the engine league able to play Musketeer Chess.
Please take a look at the Following links and join.

See http://talkchess.com/forum3/viewtopic.php?f=7&t=72572 and also interesting discussions on 

Musketeer-Stockfish ianfab/Musketeer-Stockfish#3

The rules are easily found on www.musketeerchess.net or https://github.com/fsmosca/musketeer-chess

please feel free to email me at musketeerchess (a) gmail.com for any question
Thanks

**Comment by tryingsomestuff** [comment]
Sorry I probably won't go on this topic.
